In [3]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [4]:
data = np.random.randn(7, 4)

In [5]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [6]:
data

array([[-1.45896732,  0.15330014,  1.4381091 , -0.40222741],
       [ 0.95979259,  0.61438286,  0.92941251,  0.10934799],
       [-0.14486328,  0.5630787 ,  1.75027443, -1.9300851 ],
       [-1.25429842,  0.26166748,  1.06064177, -0.30135781],
       [ 0.41043784, -0.27986244,  0.06015787,  2.2176886 ],
       [ 0.73485152, -0.65272582, -0.99958413, -1.4639693 ],
       [-0.07086501,  0.89384643, -0.42400261,  0.01395239]])

In [7]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [8]:
data[names == 'Bob']

array([[-1.45896732,  0.15330014,  1.4381091 , -0.40222741],
       [-1.25429842,  0.26166748,  1.06064177, -0.30135781]])

In [9]:
data[names == 'Bob', 2:]

array([[ 1.4381091 , -0.40222741],
       [ 1.06064177, -0.30135781]])

In [10]:
data[names == 'Bob', 3]

array([-0.40222741, -0.30135781])

In [11]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [12]:
data[~(names == 'Bob')]

array([[ 0.95979259,  0.61438286,  0.92941251,  0.10934799],
       [-0.14486328,  0.5630787 ,  1.75027443, -1.9300851 ],
       [ 0.41043784, -0.27986244,  0.06015787,  2.2176886 ],
       [ 0.73485152, -0.65272582, -0.99958413, -1.4639693 ],
       [-0.07086501,  0.89384643, -0.42400261,  0.01395239]])

In [13]:
arr = np.empty((8,4))

In [17]:
for i in range(8):
    arr[i]

In [18]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
arr= np.arange(15).reshape((3,5))

In [20]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [22]:
arr = np.random.randn(6,3)

In [23]:
arr

array([[-1.610896  ,  0.66037689,  0.91832481],
       [ 0.28576677, -0.76985077,  0.16439537],
       [ 1.76995614, -0.29822626, -0.06345362],
       [ 1.15105971, -0.05473837,  0.21357098],
       [ 1.25074592,  0.16755336, -1.08302123],
       [ 0.8833973 , -0.79069942, -0.47027456]])

In [24]:
np.dot(arr.T, arr)

array([[ 9.47908792, -2.36358587, -3.06884786],
       [-2.36358587,  1.77398274,  0.67749557],
       [-3.06884786,  0.67749557,  2.31407836]])

In [25]:
arr = np.arange(16).reshape((2,2,4))

In [26]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [27]:
arr.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [28]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [29]:
arr=np.arange(10)

In [30]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [32]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [33]:
x= np.random.randn(8)

In [34]:
y=np.random.randn(8)

In [35]:
x

array([-0.19034881,  0.0825054 ,  0.8126099 ,  1.57729898,  1.01945143,
        0.84707939, -0.70702352,  0.55493117])

In [36]:
y

array([-0.72403217, -0.33833814, -0.71784438,  0.42253516, -0.12521033,
       -2.34781867, -0.3942076 , -1.57465511])

In [37]:
np.maximum(x, y)

array([-0.19034881,  0.0825054 ,  0.8126099 ,  1.57729898,  1.01945143,
        0.84707939, -0.3942076 ,  0.55493117])

In [38]:
points = np.arange(-5, 5, 0.01)

In [39]:
xs, ys = np.meshgrid(points, points)

In [40]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [41]:
z = np.sqrt(xs **2 + ys **2)

In [42]:
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [44]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [45]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [46]:
cond = np.array([True, False, True, True, False])

In [47]:
result = [(x if c else y)
         for x, y, c in zip(xarr, yarr, cond)]

In [48]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [49]:
result = np.where(cond, xarr, yarr)

In [50]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [55]:
arr = np.random.randn(4,4)

In [56]:
arr

array([[-1.51345561,  0.66188088,  0.22285766,  1.31287761],
       [-0.69506756,  0.45062968, -0.51193608, -0.75034138],
       [-0.59926124, -0.54983933,  0.91315377,  0.16087206],
       [ 0.24773745,  0.09051138, -1.0542814 , -2.10913788]])

In [57]:
arr > 0

array([[False,  True,  True,  True],
       [False,  True, False, False],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [58]:
np.where(arr > 0, 2, -2)

array([[-2,  2,  2,  2],
       [-2,  2, -2, -2],
       [-2, -2,  2,  2],
       [ 2,  2, -2, -2]])

In [59]:
np.where(arr > 0, 2, arr)

array([[-1.51345561,  2.        ,  2.        ,  2.        ],
       [-0.69506756,  2.        , -0.51193608, -0.75034138],
       [-0.59926124, -0.54983933,  2.        ,  2.        ],
       [ 2.        ,  2.        , -1.0542814 , -2.10913788]])

In [60]:
names = np.array(['Bob', 'Joe' ,'Will', 'Bob', 'Will' , 'Joe', 'Joe'])

In [61]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [62]:
ints = np.array([3,3,3,2,2,1,1,4,4])

In [63]:
np.unique(ints)

array([1, 2, 3, 4])

In [64]:
print(ints)

[3 3 3 2 2 1 1 4 4]


In [65]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [66]:
values = np.array([6, 0,0,3,2,5,6])

In [68]:
np.in1d(values,[2,3,6])

array([ True, False, False,  True,  True, False,  True])

In [69]:
np.dot(x,y)

-2.5185050495496317

In [70]:
samples = np.random.normal(size =(4,4))

In [71]:
samples

array([[-2.11239287, -0.75776695, -0.72512274, -1.64187556],
       [-0.39035004,  0.34828658, -1.23310765, -1.21249595],
       [-1.22576487,  1.73478038,  0.08243044,  0.68545044],
       [ 0.13505578, -0.40903184, -0.85687246, -2.06411796]])

In [72]:
from random import normalvariate

In [73]:
N = 1000000

In [ ]:
%timeit samples = [normalvariate(0,1) for _ in range(N)]

In [ ]:
np.random.seed(1234)

In [2]:
import random 
.....: position = 0 
.....: walk = [position] 
.....: steps = 1000 
.....: for i in range(steps): 
.....: step = 1 if random.randint(0, 1) else -1 
.....: position += step
.....: walk.append(position)
.....:

IndentationError: expected an indented block (<ipython-input-2-cdbb3767450b>, line 6)

In [3]:
import pandas as pd

In [4]:
from pandas import Series, DataFrame

In [5]:
obj = pd.Series([4,5,-5,3])

In [6]:
obj

0    4
1    5
2   -5
3    3
dtype: int64

In [7]:
obj.values

array([ 4,  5, -5,  3], dtype=int64)

In [8]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj2 = pd.Series([4,7,-5,3], index=['d', 'b', 'a', 'c'])

In [10]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [11]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [12]:
obj2 ['a']

-5

In [13]:
obj2['d']=6

In [14]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [16]:
obj2[obj2 >0]

d    6
b    7
c    3
dtype: int64

In [17]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [19]:
import numpy as np

In [20]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [21]:
'b' in obj2

True

In [22]:
'e' in obj2

False

In [23]:
sdata= {'Ohio' : 35000, 'Texas' : 71000, 'Oregon' : 16000, 'Utah' : 5000}

In [24]:
obj3 = pd.Series(sdata)

In [25]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [26]:
states = ['California', 'Ohio', 'Oregon' ,'Texas']

In [27]:
obj4 = pd.Series(sdata, index = states)

In [28]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [30]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [31]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [32]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [33]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [34]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [35]:
obj4.name = 'population'

In [36]:
obj4.index.name = 'state'

In [37]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [38]:
obj

0    4
1    5
2   -5
3    3
dtype: int64

In [40]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [41]:
obj

Bob      4
Steve    5
Jeff    -5
Ryan     3
dtype: int64